CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS roles (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE CHECK (nombre IN ('ADMIN','RECEPCIONISTA'))
);

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rol_id SMALLINT NOT NULL REFERENCES roles(id),
  nombre VARCHAR(120) NOT NULL,
  correo VARCHAR(160) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS propietarios (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('INDIVIDUAL','EMPRESA')),
  nombre VARCHAR(150) NOT NULL,
  telefono VARCHAR(25),
  correo VARCHAR(160),
  direccion VARCHAR(250),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT propietario_contacto_chk CHECK (telefono IS NOT NULL OR correo IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS vehiculos (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  propietario_id BIGINT NOT NULL REFERENCES propietarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  tipo VARCHAR(30) NOT NULL,
  marca VARCHAR(60) NOT NULL,
  modelo VARCHAR(60) NOT NULL,
  anio SMALLINT NOT NULL CHECK (anio BETWEEN 1900 AND 2100),
  placa VARCHAR(20) NOT NULL,
  kilometraje_actual INTEGER NOT NULL DEFAULT 0 CHECK (kilometraje_actual >= 0),
  estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
  observaciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vehiculos_placa_upper ON vehiculos (UPPER(placa));
CREATE INDEX IF NOT EXISTS idx_vehiculos_propietario ON vehiculos(propietario_id);

CREATE TABLE IF NOT EXISTS servicios (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (precio >= 0),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ordenes_servicio (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vehiculo_id BIGINT NOT NULL REFERENCES vehiculos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  servicio_id BIGINT NOT NULL REFERENCES servicios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  fecha_ingreso DATE NOT NULL DEFAULT CURRENT_DATE,
  descripcion TEXT NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_PROCESO','COMPLETADO','CANCELADO')),
  prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA','MEDIA','ALTA')),
  kilometraje INTEGER NOT NULL DEFAULT 0 CHECK (kilometraje >= 0),
  costo NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (costo >= 0),
  observaciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ordenes_servicio_vehiculo ON ordenes_servicio(vehiculo_id);
CREATE INDEX IF NOT EXISTS idx_ordenes_servicio_servicio ON ordenes_servicio(servicio_id);

INSERT INTO roles(nombre) VALUES ('ADMIN'), ('RECEPCIONISTA') ON CONFLICT DO NOTHING;
INSERT INTO usuarios(rol_id,nombre,correo,password_hash)
SELECT r.id,'Administrador','admin@local.test',crypt('Admin123*',gen_salt('bf'))
FROM roles r WHERE r.nombre='ADMIN'
ON CONFLICT (correo) DO NOTHING;
